config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
   
  def index
    @tasks = Task.all
  end
  
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(task_params)
  
    if @task.save
      flash[:success] = '正常に投稿されました！'
      redirect_to @task
    else
      flash.now[:danger] = 'なにかがおかしい'
      render :new
    end
    
  end
  def edit
    @task = Task.find(params[:id])
    
  end
  def update
    @task=Task.find(params[:id])
    
    if @task.update(task_params)
      flash[:success] = "更新されました！"
      redirect_to @task
    else
      flash.now[:danger] = "更新されませんでした"
      render :edit
    end
  end
  
  def destroy
    @task=Task.find(params[:id])
    @task.destroy
    
    flash[:success] = "削除されまちた"
    redirect_to tasks_url
  end
  
  
  
  private
  def task_params
    params.require(:task).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<%= flash.each do |message_type, task| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>id:<%= @task.id %> の編集ページ！</h1>
<%= form_for(@task) do |t| %>
  <%= t.label :content,"修正入力" %>
  <%= t.text_field :content %>
  
  <%= t.submit "投稿"  %>

<% end %>

<%= link_to "一つ戻る", task_path %>
<%= link_to "一覧へ戻る", tasks_path %> 
  

app/views/tasks/index.html.erb
<h1>今日のタスクはこれ！ガンバロウ！</h1>

<ul> 
  <% @tasks.each do |task| %>
    <li> <%= link_to task.id, task %>  : <%= task.content %> </li>
  <% end %>
</ul> 

<p> <%= link_to "またタスク増やしたいドMはこちら", new_task_path %> </p>

app/views/tasks/new.html.erb
<h1>またタスク増やすの？</h1>

<%= form_for(@task) do |t| %>
  <%= t.label :content, "タスクは？" %> 
  <%= t.text_field :content %>
  
  <%= t.submit "投稿" %>
<% end %>
<%= link_to "一覧へ", tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %>のタスクリスト！！</h1>

<p><%= @task.content %></p>

<%= link_to "一覧へ！！", tasks_path %> 
<%= link_to "間違えちゃったの？♡！！", edit_task_path(@task) %> 
<%= link_to "消す♡！！", @task, method: :delete, data: {confirm: "いいのね？"} %> 